## NERD DOS DADOS - Trabalhando com arquivos Gigantes em Python

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('dados.csv', delimiter = ';', encoding = "ISO-8859-1")

In [3]:
df.head()

,CONTRATO,CLIENTE,FIADOR,DATA_CONTRATO,VALOR_TOTAL,VALOR_PARCELA,QT_MESES,UF_CLIENTE,CIDADE_CLIENTE,IDADE,SEXO,ESCOLARIDADE,QT_FILHOS,CASA_PROPRIA,OUTRO_CONTRATO_ABERTO,OUTRO_CONTRATO_QUITADO,TRABALHA_ATUALMENTE,JAN,FEV,MAR,ABR,MAI,JUN,JUL,AGO,SET,OUT,NOV,DEZ,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,X,Z,TESTE_A,TESTE_B,TESTE_C,TESTE_D,TESTE_E,TESTE_F,TESTE_G,TESTE_H,TESTE_I,TESTE_J,TESTE_K,TESTE_L,TESTE_M,TESTE_N,TESTE_O,TESTE_P,TESTE_Q,TESTE_U,TESTE_X,TESTE_W,TESTE_Y,TESTE_Z
0,1,NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS,NERD DOS DADOS,2023-12-31,100000,1000,100,SP,SAO PAULO,40,M,POS GRADUADO,2,SIM,NÃO,NÃO,SIM,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
1,2,NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS,NERD DOS DADOS,2023-12-31,100000,1000,100,RJ,RIO DE JANEIRO,40,F,SUPERIOR COMPLETO,1,NÃO,NÃO,NÃO,SIM,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
2,3,NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS,NERD DOS DADOS,2023-12-31,100000,1000,100,MG,BELO HORIZONTE,40,M,SUPERIOR CURSANDO,2,SIM,SIM,SIM,NÃO,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
3,4,NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS,NERD DOS DADOS,2023-12-31,100000,1000,100,SC,FLORIANOPOLIS,40,F,SEGUNDO GRAU COMPLETO,1,NÃO,SIM,SIM,NÃO,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100
4,5,NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS,NERD DOS DADOS,2023-12-31,100000,1000,100,BA,SALVADOR,40,M,POS GRADUADO,2,SIM,SIM,SIM,NÃO,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100

In [4]:
df.shape

(15166215, 75)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15166215 entries, 0 to 15166214
Data columns (total 75 columns):
 #   Column                  Dtype
---  ------                  -----
 0   CONTRATO                int64
 1   CLIENTE                 object
 2   FIADOR                  object
 3   DATA_CONTRATO           object
 4   VALOR_TOTAL             int64
 5   VALOR_PARCELA           int64
 6   QT_MESES                int64
 7   UF_CLIENTE              object
 8   CIDADE_CLIENTE          object
 9   IDADE                   int64
 10  SEXO                    object
 11  ESCOLARIDADE            object
 12  QT_FILHOS               int64
 13  CASA_PROPRIA            object
 14  OUTRO_CONTRATO_ABERTO   object
 15  OUTRO_CONTRATO_QUITADO  object
 16  TRABALHA_ATUALMENTE     object
 17  JAN                     int64
 18  FEV                     int64
 19  MAR                     int64
 20  ABR                     int64
 21  MAI                     int64
 22  JUN                     int64
 23  JUL                     int64
 24  AGO                     int64
 25  SET                     int64
 26  OUT                     int64
 27  NOV                     int64
 28  DEZ                     int64
 29  A                       int64
 30  B                       int64
 31  C                       int64
 32  D                       int64
 33  E                       int64
 34  F                       int64
 35  G                       int64
 36  H                       int64
 37  I                       int64
 38  J                       int64
 39  K                       int64
 40  L                       int64
 41  M                       int64
 42  N                       int64
 43  O                       int64
 44  P                       int64
 45  Q                       int64
 46  R                       int64
 47  S                       int64
 48  T                       int64
 49  U                       int64
 50  V                       int64
 51  X                       int64
 52  Z                       int64
 53  TESTE_A                 int64
 54  TESTE_B                 int64
 55  TESTE_C                 int64
 56  TESTE_D                 int64
 57  TESTE_E                 int64
 58  TESTE_F                 int64
 59  TESTE_G                 int64
 60  TESTE_H                 int64
 61  TESTE_I                 int64
 62  TESTE_J                 int64
 63  TESTE_K                 int64
 64  TESTE_L                 int64
 65  TESTE_M                 int64
 66  TESTE_N                 int64
 67  TESTE_O                 int64
 68  TESTE_P                 int64
 69  TESTE_Q                 int64
 70  TESTE_U                 int64
 71  TESTE_X                 int64
 72  TESTE_W                 int64
 73  TESTE_Y                 int64
 74  TESTE_Z                 int64
dtypes: int64(64), object(11)
memory usage: 8.5+ GB

In [6]:
# Vamos avaliar quanto está sendo usado da memória do nosso computador para cada variável
# Importante: Usar o deep = True para que seja feito uma analise profunda e traga realmente as informações precisas
memoria = df.memory_usage(deep = True)

In [7]:
memoria

Index                            128
CONTRATO                   121329720
CLIENTE                   1531787715
FIADOR                    1076801265
DATA_CONTRATO             1016136405
VALOR_TOTAL                121329720
VALOR_PARCELA              121329720
QT_MESES                   121329720
UF_CLIENTE                 894806685
CIDADE_CLIENTE             999803745
IDADE                      121329720
SEXO                       879640470
ESCOLARIDADE              1123466445
QT_FILHOS                  121329720
CASA_PROPRIA              1077967980
OUTRO_CONTRATO_ABERTO      965971620
OUTRO_CONTRATO_QUITADO     965971620
TRABALHA_ATUALMENTE       1217963340
JAN                        121329720
FEV                        121329720
MAR                        121329720
ABR                        121329720
MAI                        121329720
JUN                        121329720
JUL                        121329720
AGO                        121329720
SET                        121329720
OUT                        121329720
NOV                        121329720
DEZ                        121329720
A                          121329720
B                          121329720
C                          121329720
D                          121329720
E                          121329720
F                          121329720
G                          121329720
H                          121329720
I                          121329720
J                          121329720
K                          121329720
L                          121329720
M                          121329720
N                          121329720
O                          121329720
P                          121329720
Q                          121329720
R                          121329720
S                          121329720
T                          121329720
U                          121329720
V                          121329720
X                          121329720
Z                          121329720
TESTE_A                    121329720
TESTE_B                    121329720
TESTE_C                    121329720
TESTE_D                    121329720
TESTE_E                    121329720
TESTE_F                    121329720
TESTE_G                    121329720
TESTE_H                    121329720
TESTE_I                    121329720
TESTE_J                    121329720
TESTE_K                    121329720
TESTE_L                    121329720
TESTE_M                    121329720
TESTE_N                    121329720
TESTE_O                    121329720
TESTE_P                    121329720
TESTE_Q                    121329720
TESTE_U                    121329720
TESTE_X                    121329720
TESTE_W                    121329720
TESTE_Y                    121329720
TESTE_Z                    121329720
dtype: int64

In [8]:
memoria.sum()

19515419498

In [9]:
# Vamos achar a quantidade em Gb (GigaBytes) que está sendo utilizado da nossa RAM
# Temos a informação em Bytes, então precisamos converter até chegar em GigaBytes

# 1.024 Bytes = 1 Kb
# 1.024 Kb = 1 Mb
# 1.024 Mb = 1 Gb

# Então faremos a quantidade dos valores dividido por 1024 ao cubo
Memoria_Gb = memoria.sum() / (1024 ** 3)
Memoria_Gb

18.17515073157847

In [10]:
# Avaliando o percentual de cada coluna
memoria / memoria.sum() * 100

Index                     6.558916e-07
CONTRATO                  6.217121e-01
CLIENTE                   7.849115e+00
FIADOR                    5.517695e+00
DATA_CONTRATO             5.206839e+00
VALOR_TOTAL               6.217121e-01
VALOR_PARCELA             6.217121e-01
QT_MESES                  6.217121e-01
UF_CLIENTE                4.585127e+00
CIDADE_CLIENTE            5.123148e+00
IDADE                     6.217121e-01
SEXO                      4.507413e+00
ESCOLARIDADE              5.756814e+00
QT_FILHOS                 6.217121e-01
CASA_PROPRIA              5.523673e+00
OUTRO_CONTRATO_ABERTO     4.949787e+00
OUTRO_CONTRATO_QUITADO    4.949787e+00
TRABALHA_ATUALMENTE       6.241031e+00
JAN                       6.217121e-01
FEV                       6.217121e-01
MAR                       6.217121e-01
ABR                       6.217121e-01
MAI                       6.217121e-01
JUN                       6.217121e-01
JUL                       6.217121e-01
AGO                       6.217121e-01
SET                       6.217121e-01
OUT                       6.217121e-01
NOV                       6.217121e-01
DEZ                       6.217121e-01
A                         6.217121e-01
B                         6.217121e-01
C                         6.217121e-01
D                         6.217121e-01
E                         6.217121e-01
F                         6.217121e-01
G                         6.217121e-01
H                         6.217121e-01
I                         6.217121e-01
J                         6.217121e-01
K                         6.217121e-01
L                         6.217121e-01
M                         6.217121e-01
N                         6.217121e-01
O                         6.217121e-01
P                         6.217121e-01
Q                         6.217121e-01
R                         6.217121e-01
S                         6.217121e-01
T                         6.217121e-01
U                         6.217121e-01
V                         6.217121e-01
X                         6.217121e-01
Z                         6.217121e-01
TESTE_A                   6.217121e-01
TESTE_B                   6.217121e-01
TESTE_C                   6.217121e-01
TESTE_D                   6.217121e-01
TESTE_E                   6.217121e-01
TESTE_F                   6.217121e-01
TESTE_G                   6.217121e-01
TESTE_H                   6.217121e-01
TESTE_I                   6.217121e-01
TESTE_J                   6.217121e-01
TESTE_K                   6.217121e-01
TESTE_L                   6.217121e-01
TESTE_M                   6.217121e-01
TESTE_N                   6.217121e-01
TESTE_O                   6.217121e-01
TESTE_P                   6.217121e-01
TESTE_Q                   6.217121e-01
TESTE_U                   6.217121e-01
TESTE_X                   6.217121e-01
TESTE_W                   6.217121e-01
TESTE_Y                   6.217121e-01
TESTE_Z                   6.217121e-01
dtype: float64

## Vamos avaliar cada variavel do tipo Object

DATA_CONTRATO<br>
CLIENTE<br>
FIADOR<br> 
UF_CLIENTE<br> 
CIDADE_CLIENTE<br> 
SEXO<br>
ESCOLARIDADE<br>
CASA_PROPRIA<br>
OUTRO_CONTRATO_ABERTO<br>
OUTRO_CONTRATO_QUITADO<br>
TRABALHA_ATUALMENTE<br>

In [11]:
# Variavel Data_Contrato
df["DATA_CONTRATO"].head()

0    2023-12-31
1    2023-12-31
2    2023-12-31
3    2023-12-31
4    2023-12-31
Name: DATA_CONTRATO, dtype: object

In [12]:
# Variavel Cliente
df["CLIENTE"].value_counts()

NERD DOS DADOS - TUDO SOBRE CIENCIA DE DADOS    15166215
Name: CLIENTE, dtype: int64

In [13]:
# Variavel Fiador
df["FIADOR"].value_counts()

NERD DOS DADOS    15166215
Name: FIADOR, dtype: int64

In [14]:
# Variavel UF_Cliente
df["UF_CLIENTE"].value_counts()

SP    1166640
RJ    1166640
MG    1166640
SC    1166640
BA    1166640
DF    1166640
PR    1166625
PA    1166625
AC    1166625
AM    1166625
GO    1166625
AL    1166625
SE    1166625
Name: UF_CLIENTE, dtype: int64

In [15]:
# Variavel Cidade_Cliente
df["CIDADE_CLIENTE"].value_counts()

SAO PAULO         1166640
RIO DE JANEIRO    1166640
BELO HORIZONTE    1166640
FLORIANOPOLIS     1166640
SALVADOR          1166640
BRASILIA          1166640
CURITIBA          1166625
MARAJO            1166625
RIO BRANCO        1166625
MANAUS            1166625
GOIANIA           1166625
MACEIO            1166625
ARACAJU           1166625
Name: CIDADE_CLIENTE, dtype: int64

In [16]:
# Variavel Sexo
df["SEXO"].value_counts()

M    8166420
F    6999795
Name: SEXO, dtype: int64

In [17]:
# Variavel Escolaridade
df["ESCOLARIDADE"].value_counts()

SEGUNDO GRAU COMPLETO    4666515
POS GRADUADO             3499905
SUPERIOR COMPLETO        3499905
SUPERIOR CURSANDO        3499890
Name: ESCOLARIDADE, dtype: int64

In [18]:
# Variavel Casa Propria
df["CASA_PROPRIA"].value_counts()

SIM    8166420
NÃO    6999795
Name: CASA_PROPRIA, dtype: int64

In [19]:
# Variavel Outro Contrato Aberto
df["OUTRO_CONTRATO_ABERTO"].value_counts()

SIM    12832935
NÃO     2333280
Name: OUTRO_CONTRATO_ABERTO, dtype: int64

In [20]:
# Variavel Outro Contrato Quitado
df["OUTRO_CONTRATO_QUITADO"].value_counts()

SIM    12832935
NÃO     2333280
Name: OUTRO_CONTRATO_QUITADO, dtype: int64

In [21]:
# Variavel Trabalha Atualmente
df["TRABALHA_ATUALMENTE"].value_counts()

NÃO    12832935
SIM     2333280
Name: TRABALHA_ATUALMENTE, dtype: int64

In [22]:
# Repare o seguinte
# Variavel DATA_CONTRATO é do tipo Date
# As outras variaveis são do tipo categóricas...

# Vamos converter a variavel DATA_CONTRATO para o tipo DateTime do Pandas
df["DATA_CONTRATO"] = pd.to_datetime(df["DATA_CONTRATO"])


# Variavel CLIENTE e FIADOR iremos descarta-la, pois sabemos que não será necessário, pois já temos um numero
# de contrato representando o cliente e seu fiador
df = df.drop("CLIENTE", axis=1)
df = df.drop("FIADOR", axis=1)


# Vamos converter as outras variaves que analisamos para o tipo categorico
df["UF_CLIENTE"] = df["UF_CLIENTE"].astype("category")
df["CIDADE_CLIENTE"] = df["CIDADE_CLIENTE"].astype("category")
df["SEXO"] = df["SEXO"].astype("category")
df["ESCOLARIDADE"] = df["ESCOLARIDADE"].astype("category")
df["CASA_PROPRIA"] = df["CASA_PROPRIA"].astype("category")
df["OUTRO_CONTRATO_ABERTO"] = df["OUTRO_CONTRATO_ABERTO"].astype("category")
df["OUTRO_CONTRATO_QUITADO"] = df["OUTRO_CONTRATO_QUITADO"].astype("category")
df["TRABALHA_ATUALMENTE"] = df["TRABALHA_ATUALMENTE"].astype("category")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15166215 entries, 0 to 15166214
Data columns (total 73 columns):
 #   Column                  Dtype
---  ------                  -----
 0   CONTRATO                int64
 1   DATA_CONTRATO           datetime64[ns]
 2   VALOR_TOTAL             int64
 3   VALOR_PARCELA           int64
 4   QT_MESES                int64
 5   UF_CLIENTE              category
 6   CIDADE_CLIENTE          category
 7   IDADE                   int64
 8   SEXO                    category
 9   ESCOLARIDADE            category
 10  QT_FILHOS               int64
 11  CASA_PROPRIA            category
 12  OUTRO_CONTRATO_ABERTO   category
 13  OUTRO_CONTRATO_QUITADO  category
 14  TRABALHA_ATUALMENTE     category
 15  JAN                     int64
 16  FEV                     int64
 17  MAR                     int64
 18  ABR                     int64
 19  MAI                     int64
 20  JUN                     int64
 21  JUL                     int64
 22  AGO                     int64
 23  SET                     int64
 24  OUT                     int64
 25  NOV                     int64
 26  DEZ                     int64
 27  A                       int64
 28  B                       int64
 29  C                       int64
 30  D                       int64
 31  E                       int64
 32  F                       int64
 33  G                       int64
 34  H                       int64
 35  I                       int64
 36  J                       int64
 37  K                       int64
 38  L                       int64
 39  M                       int64
 40  N                       int64
 41  O                       int64
 42  P                       int64
 43  Q                       int64
 44  R                       int64
 45  S                       int64
 46  T                       int64
 47  U                       int64
 48  V                       int64
 49  X                       int64
 50  Z                       int64
 51  TESTE_A                 int64
 52  TESTE_B                 int64
 53  TESTE_C                 int64
 54  TESTE_D                 int64
 55  TESTE_E                 int64
 56  TESTE_F                 int64
 57  TESTE_G                 int64
 58  TESTE_H                 int64
 59  TESTE_I                 int64
 60  TESTE_J                 int64
 61  TESTE_K                 int64
 62  TESTE_L                 int64
 63  TESTE_M                 int64
 64  TESTE_N                 int64
 65  TESTE_O                 int64
 66  TESTE_P                 int64
 67  TESTE_Q                 int64
 68  TESTE_U                 int64
 69  TESTE_X                 int64
 70  TESTE_W                 int64
 71  TESTE_Y                 int64
 72  TESTE_Z                 int64
dtypes: category(8), datetime64[ns](1), int64(64)
memory usage: 7.5 GB

In [24]:
# Vamos avaliar novamente nossa memória
memoria = df.memory_usage(deep = True)  
Memoria_Gb2 = memoria.sum() / (1024 ** 3)
Memoria_Gb2

7.457813343964517

In [25]:
# Utilização da memória
print (Memoria_Gb)
print (Memoria_Gb2)

18.17515073157847
7.457813343964517

In [26]:
# Percentual de Redução
round(100 - (Memoria_Gb2 / Memoria_Gb * 100), 2)

58.97